//! Shared I/O primitives for the digest-writing blocks.
//!
//! `write_atomic`, `today_dated_path`, and `write_digest_and_emit` were
//! copy-pasted across the four digest-writing blocks. This module provides
//! single authoritative implementations. The `execute()` skeleton of each
//! block is generated by the `digest_block_execute!` macro in `macros.rs`,
//! which clones the trigger fields and `self` path fields, then dispatches
//! to the module-local `write()` function.

use std::fmt::Write as _;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use chrono::Local;
use foundry_sdk::event::EventType;
use foundry_sdk::task_block::TaskBlockResult;
use foundry_sdk::throttle::Throttle;

/// Atomically write `content` to `target`: create `dir` if absent, write to a
/// sibling `.{name}.tmp` file, fsync, then rename into place.
pub(crate) fn write_atomic(dir: &Path, target: &Path, content: &str) -> anyhow::Result<()> {
    std::fs::create_dir_all(dir)?;
    let mut tmp = target.to_path_buf();
    let file_name = target.file_name().and_then(|n| n.to_str()).unwrap_or("digest.md");
    tmp.set_file_name(format!(".{file_name}.tmp"));

    {
        let mut f = std::fs::File::create(&tmp)?;
        f.write_all(content.as_bytes())?;
        f.sync_all()?;
    }
    std::fs::rename(&tmp, target)?;
    Ok(())
}

/// Return `""` for singular (n == 1) and `"s"` for plural — used in summary lines.
pub(crate) const fn plural(n: u64) -> &'static str {
    if n == 1 { "" } else { "s" }
}

/// Render the standard agent-body digest markdown: header, italic summary line, body.
///
/// Used by the ops and commit digest writers whose structure is identical — they
/// differ only in the title and summary-line text, both supplied by the caller.
pub(crate) fn render_agent_body_digest(title: &str, summary_line: &str, body: &str) -> String {
    let mut out = String::with_capacity(body.len() + 128);
    wln!(out, "# {title}\n");
    wln!(out, "{summary_line}\n");
    let trimmed = body.trim_end();
    out.push_str(trimmed);
    if !trimmed.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Return the today-date string and the corresponding `{dir}/{YYYY-MM-DD}.md` path.
pub(crate) fn today_dated_path(dir: &Path) -> (String, PathBuf) {
    let date = Local::now().format("%Y-%m-%d").to_string();
    let path = dir.join(format!("{date}.md"));
    (date, path)
}

/// Context for a single digest write operation.
///
/// Groups the six invariant parameters that every digest writer passes identically
/// so `write_digest_and_emit` stays within clippy's argument-count limit.
pub(crate) struct DigestWrite<'a> {
    /// Short label used in log and summary messages (e.g. `"commit"`).
    pub(crate) noun: &'a str,
    pub(crate) event_type: EventType,
    pub(crate) project: &'a str,
    pub(crate) throttle: Throttle,
    pub(crate) dir: &'a Path,
    pub(crate) rendered: &'a str,
}

/// Shared orchestration skeleton for all four digest writers.
///
/// Handles the dry-run guard, atomic write, tracing, and terminal event
/// emission — the only variation across callers is the digest noun, event
/// type, and how the typed result payload is constructed.
///
/// * `ctx` — invariant write context (noun, event type, project, throttle, dir, rendered).
/// * `make_payload` — called once with `(success, digest_path)` to build the
///   serialisable terminal payload.
/// * `on_committed` — called exactly once after a successful `write_atomic`,
///   before `emit_result`. Pass `|| {}` when there is no post-commit work.
///   `WriteOpsDigest` uses this hook to advance the watermark.
pub(crate) fn write_digest_and_emit<P, F, C>(
    ctx: DigestWrite<'_>,
    make_payload: F,
    on_committed: C,
) -> anyhow::Result<TaskBlockResult>
where
    P: serde::Serialize,
    F: Fn(bool, Option<String>) -> P,
    C: FnOnce(),
{
    let (_, intended_path) = today_dated_path(ctx.dir);

    if !ctx.throttle.permits_mutation() {
        tracing::info!(
            path = %intended_path.display(),
            bytes = ctx.rendered.len(),
            "dry-run: skipping {} digest write", ctx.noun,
        );
        return super::emit_result(
            format!("dry-run: {} digest not written to {}", ctx.noun, intended_path.display()),
            ctx.event_type,
            ctx.project,
            ctx.throttle,
            &make_payload(true, None),
        );
    }

    match write_atomic(ctx.dir, &intended_path, ctx.rendered) {
        Ok(()) => {
            tracing::info!(
                path = %intended_path.display(),
                bytes = ctx.rendered.len(),
                "{} digest written", ctx.noun,
            );
            on_committed();
            super::emit_result(
                format!("{} digest written to {}", ctx.noun, intended_path.display()),
                ctx.event_type,
                ctx.project,
                ctx.throttle,
                &make_payload(true, Some(intended_path.to_string_lossy().to_string())),
            )
        }
        Err(e) => {
            tracing::warn!(
                path = %intended_path.display(),
                error = %e,
                "{} digest write failed", ctx.noun,
            );
            super::emit_result(
                format!("failed to write {} digest: {e}", ctx.noun),
                ctx.event_type,
                ctx.project,
                ctx.throttle,
                &make_payload(false, None),
            )
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plural_returns_empty_for_singular_and_s_for_plural() {
        assert_eq!(plural(1), "");
        assert_eq!(plural(0), "s");
        assert_eq!(plural(2), "s");
    }

    #[test]
    fn render_agent_body_digest_includes_header_summary_and_body() {
        let result = render_agent_body_digest(
            "Ops Digest — 2026-06-23",
            "_7 operational events._",
            "## Section\n- item\n",
        );
        assert!(result.starts_with("# Ops Digest — 2026-06-23\n"));
        assert!(result.contains("_7 operational events._"));
        assert!(result.contains("## Section"));
        assert!(result.ends_with('\n'), "must end with a single newline");
        assert!(!result.ends_with("\n\n"), "must not end with two newlines");
    }

    #[test]
    fn render_agent_body_digest_adds_trailing_newline_when_body_lacks_one() {
        let result = render_agent_body_digest(
            "Test Digest — 2026-06-23",
            "_1 event._",
            "body without newline",
        );
        assert!(result.ends_with('\n'));
    }

    #[test]
    fn write_atomic_creates_dir_writes_content_and_leaves_no_tmp() {
        let base = tempfile::tempdir().unwrap();
        let dir = base.path().join("sub");
        let target = dir.join("2026-06-14.md");

        write_atomic(&dir, &target, "hello world").unwrap();

        assert!(target.exists(), "target file must exist after write");
        let content = std::fs::read_to_string(&target).unwrap();
        assert_eq!(content, "hello world");

        let tmp = dir.join(".2026-06-14.md.tmp");
        assert!(!tmp.exists(), "tmp file must not remain after rename");
    }

    #[test]
    fn write_atomic_overwrites_existing_target() {
        let base = tempfile::tempdir().unwrap();
        let dir = base.path().to_path_buf();
        let target = dir.join("digest.md");
        std::fs::write(&target, b"old").unwrap();

        write_atomic(&dir, &target, "new").unwrap();

        let content = std::fs::read_to_string(&target).unwrap();
        assert_eq!(content, "new");
    }

    #[test]
    fn today_dated_path_returns_consistent_date_and_path() {
        let base = tempfile::tempdir().unwrap();
        let dir = base.path();
        let (date, path) = today_dated_path(dir);
        assert!(path.ends_with(format!("{date}.md")), "path must use the returned date string");
        assert_eq!(date.len(), 10, "date must be YYYY-MM-DD");
        assert!(date.chars().all(|c| c.is_ascii_digit() || c == '-'));
    }

    #[test]
    fn write_digest_and_emit_full_throttle_writes_file() {
        let base = tempfile::tempdir().unwrap();
        let dir = base.path();
        let (date, expected_path) = today_dated_path(dir);
        let rendered = format!("# Test Digest — {date}\n");

        let result = write_digest_and_emit(
            DigestWrite {
                noun: "test",
                event_type: foundry_sdk::event::EventType::CommitDigestCompleted,
                project: "test-project",
                throttle: foundry_sdk::throttle::Throttle::Full,
                dir,
                rendered: &rendered,
            },
            |success, digest_path| serde_json::json!({"success": success, "path": digest_path}),
            || {},
        )
        .unwrap();

        assert!(result.success);
        assert!(expected_path.exists(), "file must be written on full throttle");
        assert_eq!(std::fs::read_to_string(&expected_path).unwrap(), rendered);
    }

    #[test]
    fn write_digest_and_emit_dry_run_skips_write() {
        let base = tempfile::tempdir().unwrap();
        let dir = base.path();
        let (date, expected_path) = today_dated_path(dir);
        let rendered = format!("# Test Digest — {date}\n");

        let result = write_digest_and_emit(
            DigestWrite {
                noun: "test",
                event_type: foundry_sdk::event::EventType::CommitDigestCompleted,
                project: "test-project",
                throttle: foundry_sdk::throttle::Throttle::DryRun,
                dir,
                rendered: &rendered,
            },
            |success, digest_path| serde_json::json!({"success": success, "path": digest_path}),
            || {},
        )
        .unwrap();

        assert!(result.success, "dry-run must still report success");
        assert!(!expected_path.exists(), "dry-run must not write the file");
    }

    #[test]
    fn write_digest_and_emit_unwritable_dir_emits_failure() {
        let base = tempfile::tempdir().unwrap();
        let blocker = base.path().join("blocker");
        std::fs::write(&blocker, b"i am a file").unwrap();
        let unwritable = blocker.join("nested");

        let result = write_digest_and_emit(
            DigestWrite {
                noun: "test",
                event_type: foundry_sdk::event::EventType::CommitDigestCompleted,
                project: "test-project",
                throttle: foundry_sdk::throttle::Throttle::Full,
                dir: &unwritable,
                rendered: "content",
            },
            |success, digest_path| serde_json::json!({"success": success, "path": digest_path}),
            || {},
        )
        .unwrap();

        let payload: serde_json::Value = result.events[0].parse_payload().unwrap();
        assert!(!payload["success"].as_bool().unwrap());
        assert!(result.summary.contains("failed to write"));
    }
}
